### ISSUE TITLE
Connection problems after update

### ISSUE THREAD

**Issue by p33k** [ioBroker/ioBroker.fhem#21]
I have iobroker master with admin running on a windows 10 machine and iobroker client and fhem on a raspi.
everything worked with the telnet connection to fhem but since the last update the connection is gone.
the fhem instance shows only a yellow dot and doesn't connect green.
I get this error log:
`

fhem.0 | 2018-11-18 13:44:06.223 | error | at Timer.listOnTimeout (timers.js:290:5)
-- | -- | -- | --
fhem.0 | 2018-11-18 13:44:06.223 | error | at tryOnTimeout (timers.js:323:5)
fhem.0 | 2018-11-18 13:44:06.223 | error | at ontimeout (timers.js:498:11)
fhem.0 | 2018-11-18 13:44:06.223 | error | at Timeout.setTimeout [as _onTimeout] (C:\ioBroker\node_modules\iobroker.fhem\lib\telnet.js:128:60)
fhem.0 | 2018-11-18 13:44:06.223 | error | TypeError: Cannot read property 'write' of null
fhem.0 | 2018-11-18 13:44:06.223 | error | uncaught exception: Cannot read property 'write' of null
fhem.0 | 2018-11-18 13:44:06.223 | error | at Manager.ondata (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\manager.js:322:16)
fhem.0 | 2018-11-18 13:44:06.223 | error | at Decoder.add (C:\ioBroker\node_modules\socket.io-parser\index.js:246:12)
fhem.0 | 2018-11-18 13:44:06.223 | error | at Decoder.Emitter.emit (C:\ioBroker\node_modules\component-emitter\index.js:134:20)
fhem.0 | 2018-11-18 13:44:06.223 | error | at Decoder.<anonymous> (C:\ioBroker\node_modules\component-bind\index.js:21:15)
fhem.0 | 2018-11-18 13:44:06.223 | error | at Manager.ondecoded (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\manager.js:332:8)
fhem.0 | 2018-11-18 13:44:06.223 | error | at Manager.Emitter.emit (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\component-emitter\index.js:133:20)
fhem.0 | 2018-11-18 13:44:06.223 | error | at Manager.<anonymous> (C:\ioBroker\node_modules\component-bind\index.js:21:15)
fhem.0 | 2018-11-18 13:44:06.223 | error | at Socket.onpacket (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:236:12)
fhem.0 | 2018-11-18 13:44:06.223 | error | at Socket.onack (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:312:9)
fhem.0 | 2018-11-18 13:44:06.223 | error | at Socket.adapter.getState (C:\ioBroker\node_modules\iobroker.fhem\main.js:671:34)
fhem.0 | 2018-11-18 13:44:06.223 | error | TypeError: Cannot read property 'split' of null
fhem.0 | 2018-11-18 13:44:06.223 | error | uncaught exception: Cannot read property 'split' of null

`

what's the problem there?

**Comment by Apollon77** [comment]
What did you update? Fhem or iobroker Adapter?

**Comment by p33k** [comment]
removing the FHEM instance and adding it again solved the problem.
