### ISSUE TITLE
No more https://debian.fhem.de/fhem-5.8.deb 

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.fhem#3]
What does it mean for us?

```
2017-03-08 repositories stable and nightly merged
Please remove "stable" entry in file /etc/apt/sources.list if still existent.

sudo sed -i /debian.fhem.de/d /etc/apt/sources.list

You really don't need any debian.fhem.de entry in your sources after FHEM was installed successfully.
```

**Comment by Apollon77** [comment]
Means nothing in a first run, or. And http://fhem.de/fhem-5.8.deb ids also back also when I call in my browser. I will try update tesing, else we also use tar.gz on travis ...

**Comment by Apollon77** [comment]
testing fixed ... IIn the end I only needed to use the package from fhem.de ...
